### PR TITLE
feat(accessibility): enhanced keyboard accessbility and form states

### PR DESCRIPTION
**Pull request by corykon**
Started by just adding focus/hover states to form controls. I'm not married to the styles by any means, but they're pretty consistent and simple. Check them out and see what you think. They'll be easy to change now that they're all in there. Some components, like inputs and checkboxes wouldn't really accept "focus" before.

Also ended up adding keyboard accessibility features all over, so most every component can now be operated just using the keyboard. I'd recommend going component by component and tabbing around to see how things feel, and compare it to the prod site.

### CODE REVIEW

**Comment by corykon** [comment]
Web 1920 – 1

**Comment by andrew-frueh** [comment]
WOW thanks for calling this out!  I somehow totally missed the notification for this PR.  Will review by end of day.

**Comment by andrew-frueh** [comment]
Incredible work @corykon - seriously, you've outdone yourself.  As an experiment I tried naving through the examples on the site as it stands currently, and it's terribly frustrating.  But then I pulled up your PR, and it works beautifully.  Everything is consistent with the HTML standard (ie arrows for radios, etc).

The only tiny addition I'll make is that Firefox adds a dotted line to active items, which is totally unnecessary with your highlights and it looks weird.  So I'll add css to remove that.  But otherwise this is good to go.  And it's a massive upgrade for Cashmere.

Thanks so much for doing this.

**Comment by corykon** [comment]
Awesome, thanks for reviewing, and for making that extra tweak. Hope your not working this late every night during the break!

**Pull request merged**
